name: capstone_design_2022_spring
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: 0.8.5+3
  tflite: ^1.1.2
  cloud_firestore: ^3.1.18
  firebase_core: ^1.18.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/

fonts:
  - family: OpenSans
    fonts:
      - asset: fonts/OpenSans-Regular.ttf